# Generated by Django 5.1.1 on 2024-09-24 01:36

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Product', max_length=100, unique=True)),
                ('price', models.FloatField(help_text='Enter Price', max_length=100)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='insensitive-unique-product', violation_error_message='Product name already exists!')],
            },
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the Product', primary_key=True, serialize=False)),
                ('total_price', models.FloatField(help_text='Enter Total Price', max_length=100)),
                ('status', models.CharField(blank=True, choices=[('r', 'Ready'), ('p', 'Pending'), ('a', 'Approved'), ('d', 'Deny')], default='r', help_text='Product Status', max_length=1)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='grocery.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['update_date'],
            },
        ),
    ]
