# Generated by Django 5.1.1 on 2024-09-24 04:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_alter_producthistory_total_price_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, help_text='Enter Total Price', max_length=100)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='grocery.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the Order', primary_key=True, serialize=False)),
                ('total_price', models.FloatField(default=0, help_text='Enter Total Price', max_length=100)),
                ('status', models.CharField(blank=True, choices=[('p', 'Pending'), ('a', 'Approved'), ('d', 'Deny')], default='p', help_text='Product Status', max_length=1)),
                ('update_date', models.DateField(auto_now=True, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='grocery.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['update_date'],
            },
        ),
        migrations.DeleteModel(
            name='ProductHistory',
        ),
    ]
