# Generated by Django 5.1.1 on 2024-09-24 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_cart_orderhistory_delete_producthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./upload'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, help_text='Enter amount', max_length=100)),
                ('price', models.FloatField(default=0, help_text='Enter Price', max_length=100)),
                ('status', models.CharField(blank=True, choices=[('p', 'Ready'), ('a', 'Approved'), ('d', 'Deny')], default='p', help_text='Product Status', max_length=1)),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.orderhistory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='grocery.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
