# Generated by Django 5.1.1 on 2024-09-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0005_alter_product_image_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter Total Price', max_digits=10, max_length=100),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter Price', max_digits=10, max_length=100),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter Price', max_digits=10, max_length=100),
        ),
    ]
