# Generated by Django 5.1.1 on 2024-09-25 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_alter_orderhistory_total_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='status',
        ),
    ]
