# Generated by Django 5.1.1 on 2024-09-25 06:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_alter_orderhistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for the Order', primary_key=True, serialize=False),
        ),
    ]
