# Generated by Django 5.1.1 on 2024-09-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0009_alter_orderhistory_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
