# Generated by Django 5.1.1 on 2024-09-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0010_alter_orderhistory_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'ordering': ['-update_date']},
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Pending'), ('a', 'Approved'), ('d', 'Denied')], default='p', help_text='Product Status', max_length=1),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Enter Total Price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
